apiVersion: v1
kind: Pod
metadata:
  name: msn-test
  annotations:
    tunnel/address: "10.0.0.0/24"
    tunnel/port: "1234"
    tunnel/dns: |
      search default.svc.cluster.local svc.cluster.local cluster.local europe-west1-c.c.gowish-devx.internal c.gowish-devx.internal google.internal
      nameserver 169.254.20.10
    tunnel/routes: |
      172.23.0.0/16 
      172.20.248.0/22
      169.254.20.10/32
spec:
  containers:
  - name: tunnel
    image: ghcr.io/mikkelsnitker/tunnel:latest
    
    env:
      - name: TUNNEL_PORT
        value: "1234"
      - name: TUNNEL_NETWORK
        value: "10.0.0.1/24"
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
      privileged: true
    stdin: true
    tty: true
  restartPolicy: Never
